import { createEvent, deleteEvent, updateAttendance } from "@/app/actions";
import { db } from "@/lib/db";
import { ConfirmSubmitButton } from "@/components/confirm-submit-button";
export const dynamic = "force-dynamic";
export default async function Events({ searchParams }: { searchParams: Promise<{ deleted?: string; attendance_updated?: string; error?: string }> }) {
  const { deleted, attendance_updated, error } = await searchParams;
  const { data } = await db().from("events").select("*,reservations(id,status,user:users(name,has_racket))").order("starts_at", { ascending: false });
  return <section className="admin-page"><div className="page-title"><div><p className="eyebrow green">EVENTS</p><h1>イベント管理</h1><p>練習・イベントの作成と参加者確認ができます。</p></div></div>
    {deleted && <div className="success-message">イベントを削除しました。</div>}
    {attendance_updated && <div className="success-message">参加状況を更新しました。</div>}
    {error && <div className="alert">{error === "attendance" ? "参加状況を更新できませんでした。" : "イベントを削除できませんでした。もう一度お試しください。"}</div>}
    <details className="create-panel"><summary>＋ 新しい予定を作成</summary><form action={createEvent} className="grid-form"><label className="full">種別<select name="event_type" defaultValue="tennis"><option value="tennis">テニス</option><option value="event">イベント</option></select></label><label>タイトル<input name="title" required /></label><label>場所<input name="location" required /></label><label>開始日時<input type="datetime-local" name="starts_at" required /></label><label>終了日時<input type="datetime-local" name="ends_at" required /></label><label>定員<input type="number" name="capacity" min="1" required /></label><label className="full">説明<textarea name="description" /></label><button className="primary full">予定を作成</button></form></details>
    <div className="admin-cards">{data?.map(e => { const active = e.reservations.filter((r: {status:string}) => r.status !== "cancelled"); const reserved = active.filter((r: {status:string}) => r.status === "reserved"); const rackets = reserved.filter((r: {user:{has_racket:boolean}}) => !r.user?.has_racket).length; return <article className="admin-event" key={e.id}><div><span className="event-chip">{new Date(e.starts_at).toLocaleDateString("ja-JP")}・{e.event_type === "tennis" ? "テニス" : "イベント"}</span><h3>{e.title}</h3><p>{e.location}・{new Date(e.starts_at).toLocaleTimeString("ja-JP", { hour: "2-digit", minute: "2-digit" })}</p></div><div className="admin-event-stats"><span><strong>{reserved.length}/{e.capacity}</strong><small>予約</small></span>{e.event_type === "tennis" && <span><strong>{rackets}</strong><small>貸出ラケット</small></span>}<form action={deleteEvent}><input type="hidden" name="event_id" value={e.id} /><ConfirmSubmitButton className="danger event-delete" message={`「${e.title}」を削除しますか？参加予約もすべて削除され、元に戻せません。`}>削除</ConfirmSubmitButton></form></div><details><summary>参加者を表示</summary><ul className="attendance-list">{active.map((r: {id:string,status:string,user:{name:string,has_racket:boolean}}) => <li key={r.id}><span>{r.user?.name}{e.event_type === "tennis" && !r.user?.has_racket ? "（ラケット貸出）" : ""}</span><form action={updateAttendance}><input type="hidden" name="id" value={r.id} /><select name="status" defaultValue={r.status}><option value="reserved">予約</option><option value="attended">参加済み</option><option value="cancelled">キャンセル</option></select><button className="table-action">更新</button></form></li>)}</ul></details></article>; })}</div>
  </section>;
}
