import { createEvent } from "@/app/actions";
import { db } from "@/lib/db";
export const dynamic = "force-dynamic";
export default async function Events() {
  const { data } = await db().from("events").select("*,reservations(id,status,user:users(name,has_racket))").order("starts_at", { ascending: false });
  return <section className="admin-page"><div className="page-title"><div><p className="eyebrow green">EVENTS</p><h1>イベント管理</h1><p>練習・イベントの作成と参加者確認ができます。</p></div></div>
    <details className="create-panel"><summary>＋ 新しい予定を作成</summary><form action={createEvent} className="grid-form"><label className="full">種別<select name="event_type" defaultValue="tennis"><option value="tennis">テニス</option><option value="event">イベント</option></select></label><label>タイトル<input name="title" required /></label><label>場所<input name="location" required /></label><label>開始日時<input type="datetime-local" name="starts_at" required /></label><label>終了日時<input type="datetime-local" name="ends_at" required /></label><label>定員<input type="number" name="capacity" min="1" required /></label><label className="full">説明<textarea name="description" /></label><button className="primary full">予定を作成</button></form></details>
    <div className="admin-cards">{data?.map(e => { const reserved = e.reservations.filter((r: {status:string}) => r.status === "reserved"); const rackets = reserved.filter((r: {user:{has_racket:boolean}}) => !r.user?.has_racket).length; return <article className="admin-event" key={e.id}><div><span className="event-chip">{new Date(e.starts_at).toLocaleDateString("ja-JP")}・{e.event_type === "tennis" ? "テニス" : "イベント"}</span><h3>{e.title}</h3><p>{e.location}・{new Date(e.starts_at).toLocaleTimeString("ja-JP", { hour: "2-digit", minute: "2-digit" })}</p></div><div className="admin-event-stats"><span><strong>{reserved.length}/{e.capacity}</strong><small>予約</small></span>{e.event_type === "tennis" && <span><strong>{rackets}</strong><small>貸出ラケット</small></span>}</div><details><summary>参加者を表示</summary><ul>{reserved.map((r: {id:string,user:{name:string,has_racket:boolean}}) => <li key={r.id}>{r.user?.name}{e.event_type === "tennis" && !r.user?.has_racket ? "（ラケット貸出）" : ""}</li>)}</ul></details></article>; })}</div>
  </section>;
}
